server:
  port: 9000
  error:
    whitelabel:
      enabled: true
    path: /error

spring:
  application:
    name: rococo-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rococo_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&sslMode=DISABLED&allowPublicKeyRetrieval=true
    username: rococo
    password: rococo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    locations: classpath:db/migration/rococo