services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: rococo_auth
      MYSQL_USER: rococo
      MYSQL_PASSWORD: rococo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql
volumes:
  db: {}